# Generated by Django 6.0.7 on 2026-07-30 15:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='Owner User ID', max_length=128)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('genre', models.CharField(blank=True, default='Dark Academia / Fantasy', max_length=100)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('target_word_count', models.PositiveIntegerField(default=50000, help_text='Target word count goal for the project', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'lorevault_projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('Protagonist', 'Protagonist'), ('Antagonist', 'Antagonist'), ('Supporting', 'Supporting'), ('Minor', 'Minor')], db_index=True, default='Supporting', max_length=32)),
                ('age', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('physical_description', models.TextField(blank=True, default='')),
                ('backstory', models.TextField(blank=True, default='')),
                ('internal_desire', models.TextField(blank=True, default='', help_text='Core motivation or goal driving the character')),
                ('flaw', models.TextField(blank=True, default='', help_text='Fatal flaw or emotional vulnerability')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.project')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'db_table': 'lorevault_characters',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text='Rich text or Markdown manuscript body')),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0, help_text='Sequential ordering index within the project')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Completed', 'Completed')], db_index=True, default='Draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.project')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'lorevault_chapters',
                'ordering': ['project', 'order_index', 'created_at'],
                'unique_together': {('project', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp_in_story', models.CharField(default='Day 1', help_text="In-universe date or timestamp (e.g. 'Year 142 of the Eclipse, Day 4')", max_length=255)),
                ('sequence_order', models.PositiveIntegerField(db_index=True, default=1, help_text='Chronological sequence order of the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='api.chapter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.project')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'db_table': 'lorevault_timeline_events',
                'ordering': ['project', 'sequence_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('Rival', 'Rival'), ('Ally', 'Ally'), ('Family', 'Family'), ('Lovers', 'Lovers')], db_index=True, default='Ally', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_initiated', to='api.character')),
                ('character_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_received', to='api.character')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='api.project')),
            ],
            options={
                'verbose_name': 'Character Relationship',
                'verbose_name_plural': 'Character Relationships',
                'db_table': 'lorevault_character_relationships',
                'ordering': ['project', 'relationship_type'],
                'unique_together': {('character_from', 'character_to')},
            },
        ),
    ]
