# Generated by Django 6.0.7 on 2026-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_id',
            field=models.CharField(db_index=True, default='default-user', help_text='Owner User ID', max_length=128),
        ),
    ]
